TOTAL_HOURS = 'Total hours'
TOTAL_HOURS_START = 'Total hours at begin'
ALL_WORKERS_IN_TEAM = ['Yael Hadad', 'Chanel Michaeli', 'Elad Motzny', 'Maayan Lavi']
NAME = 'Name'
TOTAL = "Total hours"
TOTAL_START = "Total hours at begin"
TASK = 'Task'
IS_UNIQUE = "Is the task Unique?"
ALLOTTED_TIME = "Allotted time"
BUDGET_UNIQUE = 'Total time for less important unique tasks'
PRIORITY = 'Queue'
SUBJECT = "Subject"
DESCRIPTION = 'Description'
ESTIMATED_TIME = 'Allotted time'
Review_TIME = "Review Time"
ASSIGNEE = 'Assignee'
STATUS = 'Status'
PREV = 'Previous'
CURRENT = 'Current'
PROGRESSIVE = 'Progressive'
REVIEW = 'Review'
FIRST = 0
ID = "ID"
PRIORITY_A = 'A'
PRIORITY_B = 'B'
PRIORITY_C = 'C'
PREV_INDEX = 1
ROLE = "Role"
EXPERTISE = "Expertise"
BUDGET_FOR_UNIQUE_BELLOW = "Total time for less important unique tasks"
SPRINT = "Sprint"
IDENTIFIER = "ID"
IS_ASSIGNED = "Assigned from last sprint"
IMPOSSIBLE = "IMPOSSIBLE"
ONE = 1
ZERO = 0
UNIQUE = True
NOT_UNIQUE = False
ASSIGNED_PREV = 'Assigned from last sprint'
IS_ASSIGNED_UNIQUE = "Is assigned unique?"
PREVIOUS = "Previous"
UPDATE_UNIQUE = "Should be update as unique?"
Removed = "Should be removed?"
